services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ola
      POSTGRES_USER: ola
      POSTGRES_PASSWORD: ola
    volumes:
      - ./.data/postgres:/var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
